version: '2'

services:
  ParserM3UDotNet:
    network_mode: "service:your_jellyfin"
    image: ghcr.io/jeremielec/parsem3udotnet:main
    environment:
      - SETTINGS_JSON=/tmp/settings.json
    volumes:
      - ./settings.json:/tmp/settings.json
      - /tmp/output/:/tmp/output/


    
